### ISSUE TITLE
Syslog configuration for FreeRtr

### ISSUE THREAD

**Issue by tducatelle-criann** [rare-freertr/validated-design#5]
Hi all,

Would there be a particular configuration so that features such as syslog can succeed?
For more context, I configured a freertr with a syslog that normally sends its logs to a server in debug mode:
```logging syslog debug system 195.221.26.202```

But when I listen to the outgoing interface absolutely nothing comes out except BGP exchanges. The networks are well declared because they are pingable.

I tried with another device in the same network and the logs reach the server.

**Comment by frederic-loui** [comment]
Hi as discussed, you need to create a `proxy-profile` expected `source interface` and indicate freeRtr to use it with `client proxy <YOUR_PROFILE>`

**Comment by mc36** [comment]
actually there is a "logging proxy <prfl>" knob if you wanna alter these 1-by-1....

**Comment by mc36** [comment]
regarding the bgp exchange, one should configure a bmp session from the important sessions where a rare/freertr can replay it in realtime moreover save it to the flash in mrt format. that one needs to be archived for a year or so...
